name: Gerar e publicar documentação

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Gerar documentação
        run: make docs

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
